language: cpp
compiler: clang
before_install:
- yes | sudo add-apt-repository ppa:deadsnakes/ppa
- sudo apt-get update
- sudo apt-get install python3.6
script: python3.6 build-skia.py --branch=chrome/m72
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
    - "libskia-linux-x64.so"
    - "libskia-linux-x64.a"
    - "skia-headers.tar.gz"
  skip_cleanup: true
  on:
    tags: true
