language: cpp
compiler: clang
os:
    - linux
    - osx

before_install:
    - if [ `uname` = "Linux" ]; then
        yes | sudo add-apt-repository ppa:deadsnakes/ppa;
        sudo apt-get update;
        sudo apt-get install python3.6;
      elif [ `uname` = "Darwin" ]; then
        echo "Darwin";
      fi
script: 
    - if [ `uname` = "Linux" ]; then
        python3.6 build-skia-linux.py --branch=master;
      elif [ `uname` = "Darwin" ]; then
        python3 build-skia-mac.py --branch=master;
      fi
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
    - "libskia-linux-x64.so"
    - "libskia-linux-x64.a"
    - "skia-headers-linux.tar.gz"
    - "skia-all-linux.tar.gz"
    - "libskia-darwin-x64.so"
    - "libskia-darwin-x64.a"
    - "skia-headers-darwin.tar.gz"
    - "skia-all-darwin.tar.gz"
  skip_cleanup: true
  on:
    tags: true
